[package]
name = "desktop_switcher"
version = "0.1.0"
edition = "2021"

[dependencies]
winvd = "0.0.48"
windows = { version = "0.58.0", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging", "Win32_System_Com"] }
